export const web3Constants = {
  WEB3_INITIALIZED: 'WEB3_INITIALIZED',
  WEB3_WALLET_INITIALIZED: 'WEB3_WALLET_INITIALIZED',
  WEB3_BALANCE_INITIALIZED: 'WEB3_BALANCE_INITIALIZED',
  WEB3_NETWORK_INITIALIZED: 'WEB3_NETWORK_INITIALIZED',
};
